(() => {
const p=new URLSearchParams(location.search),code=window.NCD_POT_PLANT_LANGUAGES?.[p.get("lang")||"en"]?(p.get("lang")||"en"):"en",lang=window.NCD_POT_PLANT_LANGUAGES[code];
const INPUT=["EL","GBM","PS","ES","IWS","HSG","NOE","LR"],ORDER=["LR","EL","ES","GBM","NOE","IWS","PS","HSG"],fills=["#477B39","#727145","#926550","#9A5C5E","#786071","#526082","#436777","#44725C"];
const defaultPrimary=[63.7161,71.4877,69.0780,61.5055,57.4457,63.8039,80.6663,54.5301],defaultComparison=[55.4258,66.7686,73.5022,55.5819,61.9411,54.1229,70.6579,51.2541];
const parse=(keys,d)=>{for(const key of keys){const s=p.get(key);if(s){const a=s.split(",").map(Number);if(a.length===8&&a.every(Number.isFinite))return a}}return [...d]};
let primary=parse(["primary","under30","before"],defaultPrimary),comparison=parse(["comparison","over30","after"],defaultComparison),perspectiveOn=false,perspectiveFrame=null;
const svg=document.getElementById("viz"),defs=svg.querySelector("defs"),wg=document.getElementById("wedges"),pg=document.getElementById("labelPaths"),lg=document.getElementById("labels"),perspective=document.getElementById("perspective"),spiral=document.getElementById("spiral"),under=document.getElementById("spiralUnder"),dot=document.getElementById("stopDot");
const cx=440,cy=440,start=-112.5,deg=45,minR=108,gap=36,labelR=minR+7*gap+60,b=33/(2*Math.PI),INITIAL_R=24,WEDGE_MS=3000,SPIRAL_DELAY=2600;
const map=s=>Object.fromEntries(INPUT.map((k,i)=>[k,s[i]])),diagram=s=>{const m=map(s);return ORDER.map(k=>m[k])},ranks=v=>{const ix=v.map((_,i)=>i).sort((a,b)=>v[a]-v[b]),r=[];ix.forEach((x,i)=>r[x]=i+1);return r},rad=d=>d*Math.PI/180,polar=(r,t)=>[cx+r*Math.cos(t),cy+r*Math.sin(t)],rr=r=>minR+(r-1)*gap;
function wedgeD(i,r){const a=polar(r,rad(start+i*deg)),z=polar(r,rad(start+(i+1)*deg));return `M ${cx} ${cy} L ${a[0]} ${a[1]} A ${r} ${r} 0 0 1 ${z[0]} ${z[1]} Z`}
function arcD(i,r,inset=5){const a0=rad(start+i*deg+inset),a1=rad(start+(i+1)*deg-inset),a=polar(r,a0),z=polar(r,a1);return `M ${a[0]} ${a[1]} A ${r} ${r} 0 0 1 ${z[0]} ${z[1]}`}
function grad(i){let g=document.getElementById("cohortGrad"+i);if(!g){g=document.createElementNS("http://www.w3.org/2000/svg","linearGradient");g.id="cohortGrad"+i;g.setAttribute("x2","100%");g.setAttribute("y2","100%");g.innerHTML=`<stop offset="0%" stop-color="${fills[i]}" stop-opacity=".92"/><stop offset="100%" stop-color="${fills[i]}" stop-opacity=".72"/>`;defs.appendChild(g)}return"url(#cohortGrad"+i+")"}
function labels(){pg.innerHTML=lg.innerHTML="";ORDER.forEach((k,i)=>{const q=lang.qcs[k],mid=start+(i+.5)*deg,n=((mid%360)+360)%360,bot=n>0&&n<180,lines=q.lines.slice(0,4),c=(lines.length-1)/2;lines.forEach((line,j)=>{const off=(c-j)*34*(lang.labelLineSpacing??1),r=labelR+(bot?-off:off),id=`coa${i}_${j}`,path=document.createElementNS("http://www.w3.org/2000/svg","path");path.id=id;let s=rad(start+i*deg+3.5),e=rad(start+(i+1)*deg-3.5);if(bot)[s,e]=[e,s];const a=polar(r,s),z=polar(r,e);path.setAttribute("d",`M ${a[0]} ${a[1]} A ${r} ${r} 0 0 ${bot?0:1} ${z[0]} ${z[1]}`);path.setAttribute("fill","none");path.setAttribute("stroke","none");pg.appendChild(path);const t=document.createElementNS("http://www.w3.org/2000/svg","text");t.setAttribute("class",(line.emphasis?"arc-label-adj":"arc-label-noun")+" qc-clickable");t.setAttribute("font-size",(line.emphasis?41.5:33.5)*(lang.labelScale??1));const tp=document.createElementNS("http://www.w3.org/2000/svg","textPath");tp.setAttribute("href","#"+id);tp.setAttribute("startOffset","50%");tp.setAttribute("text-anchor","middle");tp.textContent=line.text;t.appendChild(tp);t.addEventListener("click",()=>openCard(i));lg.appendChild(t)})})}
function draw(){wg.innerHTML="";const d=diagram(primary),rs=ranks(d);ORDER.forEach((k,i)=>{const x=document.createElementNS("http://www.w3.org/2000/svg","path");x.classList.add("wedge");x.setAttribute("fill",grad(i));x.dataset.radius=rr(rs[i]);x.setAttribute("d",wedgeD(i,rr(rs[i])));x.addEventListener("click",()=>openCard(i));wg.appendChild(x)});drawPerspective();return{d,rs,min:d.indexOf(Math.min(...d))}}
function drawPerspective(radius=null,visible=perspectiveOn){perspective.innerHTML="";const d=diagram(primary),cr=ranks(diagram(comparison)),min=d.indexOf(Math.min(...d)),a=document.createElementNS("http://www.w3.org/2000/svg","path");a.setAttribute("d",arcD(min,radius??rr(cr[min])));a.setAttribute("class","over30-arc"+(visible?" visible":""));perspective.appendChild(a)}
function animatePerspectiveIn(){if(perspectiveFrame)cancelAnimationFrame(perspectiveFrame);const d=diagram(primary),cr=ranks(diagram(comparison)),min=d.indexOf(Math.min(...d)),target=rr(cr[min]),from=12,duration=1800,st=performance.now();drawPerspective(from,true);function f(now){const t=Math.min(1,(now-st)/duration),e=1-Math.pow(1-t,2.35),r=from+(target-from)*e;drawPerspective(r,true);if(t<1)perspectiveFrame=requestAnimationFrame(f);else perspectiveFrame=null}perspectiveFrame=requestAnimationFrame(f)}
const card=document.getElementById("qcCard");function openCard(i){const q=lang.qcs[ORDER[i]];if(!card)return;document.getElementById("qcCardName").textContent=q.name;document.getElementById("qcCardQuestion").textContent=q.heartQuestion;document.getElementById("qcCardDescription").textContent=q.description;card.classList.add("is-open");card.setAttribute("aria-hidden","false")}function closeCard(){card?.classList.remove("is-open");card?.setAttribute("aria-hidden","true")}document.getElementById("qcCardClose")?.addEventListener("click",closeCard);
function sector(t){let d=t*180/Math.PI;while(d<start)d+=360;while(d>=start+360)d-=360;return Math.floor((d-start)/deg)}
function spiralPts(rs,min){const t0=-Math.PI/2,max=t0+Math.PI*60,st=.0045,pts=[[cx,cy]],boundary=rr(rs[min]);let prev=t0,ps=sector(prev);for(let t=t0+st;t<=max;t+=st){const cs=sector(t);if(cs!==ps){let bt=rad(start+(ps+1)*deg);while(bt<=prev)bt+=2*Math.PI;while(bt>t)bt-=2*Math.PI;const br=b*(bt-t0);if(cs===min&&br>boundary){pts.push(polar(br,bt));return pts}}pts.push(polar(b*(t-t0),t));prev=t;ps=cs}return pts}
const pathOf=(a,n=a.length)=>{let d=`M ${a[0][0]} ${a[0][1]}`;for(let i=1;i<n;i++)d+=` L ${a[i][0].toFixed(2)} ${a[i][1].toFixed(2)}`;return d};
function clearSpiral(){spiral.setAttribute("d","");under.setAttribute("d","");dot.style.opacity=0}
function growSpiral(rs,min,delay=0){clearSpiral();setTimeout(()=>{const pts=spiralPts(rs,min),duration=Math.max(3600,pts.length*.38),st=performance.now();function f(now){const t=Math.min(1,(now-st)/duration),e=1-Math.pow(1-t,3.2),n=Math.max(2,Math.floor(e*(pts.length-1))+1),d=pathOf(pts,n);spiral.setAttribute("d",d);under.setAttribute("d",d);const q=pts[n-1];dot.setAttribute("cx",q[0]);dot.setAttribute("cy",q[1]);dot.style.opacity=1;if(t<1)requestAnimationFrame(f)}requestAnimationFrame(f)},delay)}
function animateWedges(rs){[...wg.children].forEach((w,i)=>{w.setAttribute("d",wedgeD(i,INITIAL_R));w.dataset.radius=INITIAL_R});const st=performance.now();function f(now){const t=Math.min(1,(now-st)/WEDGE_MS),e=1-Math.pow(1-t,2.15);[...wg.children].forEach((w,i)=>{const r=INITIAL_R+(rr(rs[i])-INITIAL_R)*e;w.setAttribute("d",wedgeD(i,r))});if(t<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
function togglePerspective(){perspectiveOn=!perspectiveOn;if(perspectiveOn)animatePerspectiveIn();else drawPerspective(null,false);const btn=document.getElementById("perspectiveBtn");if(btn){btn.classList.toggle("active",perspectiveOn);btn.textContent=perspectiveOn?"Hide Over-30 comparison":"Compare with Over 30"}}
document.getElementById("perspectiveBtn")?.addEventListener("click",togglePerspective);
function resetPerspective(){perspectiveOn=false;if(perspectiveFrame){cancelAnimationFrame(perspectiveFrame);perspectiveFrame=null}drawPerspective(null,false);const btn=document.getElementById("perspectiveBtn");if(btn){btn.classList.remove("active");btn.textContent="Compare with Over 30"}}
function updateUrl(){const q=new URLSearchParams(location.search);q.set("lang",code);q.set("primary",primary.join(","));q.set("comparison",comparison.join(","));history.replaceState(null,"",location.pathname+"?"+q)}
function controls(id,arr){const el=document.getElementById(id);if(!el)return;el.innerHTML="";INPUT.forEach((k,i)=>{const row=document.createElement("div");row.className="cohort-row";row.innerHTML=`<label>${lang.qcs[k].name}</label><input type="number" step="0.1" value="${Number(arr[i]).toFixed(1)}">`;row.querySelector("input").addEventListener("change",e=>{const n=Number(e.target.value);if(Number.isFinite(n)){arr[i]=n;updateUrl();resetPerspective();const x=draw();clearSpiral();growSpiral(x.rs,x.min,300)}});el.appendChild(row)})}
labels();const state=draw();controls("primaryScores",primary);controls("comparisonScores",comparison);document.getElementById("languageSelect")?.addEventListener("change",e=>{const q=new URLSearchParams(location.search);q.set("lang",e.target.value);location.search=q});const ls=document.getElementById("languageSelect");if(ls)ls.value=code;
const viewer=document.body.classList.contains("cohort-viewer"),grow=document.getElementById("growBtn");if(viewer){clearSpiral();perspective.innerHTML="";[...wg.children].forEach((w,i)=>{w.setAttribute("d",wedgeD(i,0));w.style.opacity="0"});grow?.addEventListener("click",()=>{resetPerspective();const pb=document.getElementById("perspectiveBtn");if(pb){pb.classList.remove("active");pb.textContent="Compare with Over 30"}document.body.classList.remove("has-grown");document.body.classList.add("growing");document.getElementById("perspectiveBtn")?.classList.add("available");grow.classList.add("is-running");[...wg.children].forEach(w=>w.style.opacity="");animateWedges(state.rs);growSpiral(state.rs,state.min,SPIRAL_DELAY);setTimeout(()=>{document.body.classList.remove("growing");document.body.classList.add("has-grown");grow.classList.remove("is-running");grow.querySelector(".grow-icon").textContent="🌱";grow.querySelector(".grow-label").textContent=lang.interface.watchAgain},SPIRAL_DELAY+10000)})}else{animateWedges(state.rs);growSpiral(state.rs,state.min,SPIRAL_DELAY)}
})();