(() => {
  const exportBtn=document.getElementById("exportVideoBtn"); if(!exportBtn)return;
  const churchNameInput=document.getElementById("churchNameInput"),filenamePreview=document.getElementById("exportFilenamePreview");
  const SIZE=1080,FPS=30,EXPORT_VIEWBOX={x:-100,y:-100,width:1080,height:1080},EXPORT_VIEWBOX_STRING=`${EXPORT_VIEWBOX.x} ${EXPORT_VIEWBOX.y} ${EXPORT_VIEWBOX.width} ${EXPORT_VIEWBOX.height}`;
  const INITIAL_FRAMES=Math.round(.35*FPS),REVEAL_FRAMES=FPS,SPIRAL_FRAMES=10*FPS,GOLD_FRAMES=Math.round(.5*FPS),FINAL_FRAMES=FPS;
  const sleep=ms=>new Promise(r=>setTimeout(r,ms));
  function safeFilenamePart(v){return v.trim().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");}
  function exportBaseName(){const l=new URLSearchParams(location.search).get("lang")||"en",c=safeFilenamePart(churchNameInput?.value||"");return `${c?c+"-":""}ncd-pot-plant-comparison-${l}`;}
  function updateFilenamePreview(){if(filenamePreview)filenamePreview.textContent=`${exportBaseName()}.mp4`;}
  churchNameInput?.addEventListener("input",updateFilenamePreview);updateFilenamePreview();
  function makeViewerUrl(){const c=new URLSearchParams(location.search),v=new URLSearchParams();if(c.get("before"))v.set("before",c.get("before"));if(c.get("after"))v.set("after",c.get("after"));v.set("lang",c.get("lang")||"en");v.set("export","1");return `/ncd-prototypes/pot-plant/compare/view/?${v}`;}
  function makeHiddenViewer(){const f=document.createElement("iframe");f.src=makeViewerUrl();f.setAttribute("aria-hidden","true");Object.assign(f.style,{position:"fixed",left:"0",top:"0",width:"1080px",height:"1080px",border:"0",pointerEvents:"none",opacity:"0",visibility:"hidden",zIndex:"-9999"});document.body.appendChild(f);return f;}
  async function waitForViewer(f){const deadline=Date.now()+15000;while(Date.now()<deadline){try{const doc=f.contentDocument,win=f.contentWindow;if(doc?.readyState==="complete"&&doc.getElementById("viz")&&win?.NCDPotPlantCompareExport)return{doc,win,svg:doc.getElementById("viz"),api:win.NCDPotPlantCompareExport};}catch(e){}await sleep(100);}throw new Error("The export viewer could not initialise. Please reload the page and try again.");}
  function prepareSvgClone(sourceSvg){
    const clone=sourceSvg.cloneNode(true),src=[sourceSvg,...sourceSvg.querySelectorAll("*")],dst=[clone,...clone.querySelectorAll("*")],props=["fill","fill-opacity","stroke","stroke-opacity","stroke-width","stroke-linecap","stroke-linejoin","opacity","visibility","transform","transform-origin"];
    src.forEach((s,i)=>{const d=dst[i];if(!d||!(s instanceof Element))return;const st=s.ownerDocument.defaultView.getComputedStyle(s);props.forEach(p=>{const v=st.getPropertyValue(p);if(v)d.style.setProperty(p,v);});});
    const liveWedges=sourceSvg.querySelectorAll(".wedge");clone.querySelectorAll(".wedge").forEach((w,i)=>{const st=liveWedges[i].ownerDocument.defaultView.getComputedStyle(liveWedges[i]),o=st.opacity||"0";w.setAttribute("fill",`url(#cg${i})`);w.style.fill=`url(#cg${i})`;w.setAttribute("opacity",o);w.style.opacity=o;});
    const spiral=clone.querySelector("#spiral"),under=clone.querySelector("#spiralUnder"),dot=clone.querySelector("#stopDot"),oldDot=clone.querySelector("#oldStopDot");
    if(spiral){const s=sourceSvg.querySelector("#spiral"),st=s.ownerDocument.defaultView.getComputedStyle(s);spiral.removeAttribute("filter");spiral.style.filter="none";spiral.setAttribute("stroke",st.stroke||"#e0b62a");spiral.style.stroke=st.stroke||"#e0b62a";spiral.setAttribute("stroke-opacity",st.strokeOpacity||".86");spiral.style.strokeOpacity=st.strokeOpacity||".86";spiral.setAttribute("stroke-width","8");spiral.style.strokeWidth="8px";}
    if(under){const s=sourceSvg.querySelector("#spiralUnder"),st=s.ownerDocument.defaultView.getComputedStyle(s);under.removeAttribute("filter");under.style.filter="none";under.setAttribute("stroke",st.stroke||"#e0b62a");under.style.stroke=st.stroke||"#e0b62a";under.setAttribute("stroke-opacity",st.strokeOpacity||".16");under.style.strokeOpacity=st.strokeOpacity||".16";under.setAttribute("stroke-width","12");under.style.strokeWidth="12px";}
    if(dot){const s=sourceSvg.querySelector("#stopDot"),st=s.ownerDocument.defaultView.getComputedStyle(s);dot.removeAttribute("filter");dot.style.filter="none";dot.setAttribute("fill","#e0b62a");dot.style.fill="#e0b62a";dot.setAttribute("opacity",st.opacity||"0");dot.style.opacity=st.opacity||"0";}
    if(oldDot){const s=sourceSvg.querySelector("#oldStopDot"),st=s.ownerDocument.defaultView.getComputedStyle(s);oldDot.removeAttribute("filter");oldDot.style.filter="none";oldDot.setAttribute("fill","#e0b62a");oldDot.style.fill="#e0b62a";oldDot.setAttribute("stroke","#ffffff");oldDot.style.stroke="#ffffff";oldDot.setAttribute("stroke-width","4");oldDot.style.strokeWidth="4px";oldDot.setAttribute("opacity",st.opacity||"0");oldDot.style.opacity=st.opacity||"0";}
    clone.querySelector("#labels")?.remove();clone.querySelector("#labelPaths")?.remove();clone.setAttribute("viewBox",EXPORT_VIEWBOX_STRING);clone.setAttribute("width",SIZE);clone.setAttribute("height",SIZE);clone.setAttribute("xmlns","http://www.w3.org/2000/svg");clone.setAttribute("xmlns:xlink","http://www.w3.org/1999/xlink");clone.querySelectorAll("[tabindex]").forEach(e=>e.removeAttribute("tabindex"));return clone;
  }
  function svgToCanvasPoint(p){return{x:(p.x-EXPORT_VIEWBOX.x)*(SIZE/EXPORT_VIEWBOX.width),y:(p.y-EXPORT_VIEWBOX.y)*(SIZE/EXPORT_VIEWBOX.height)};}
  function makeShapedLine(text,st,fill){const fontSize=parseFloat(st.fontSize)||34,fontWeight=st.fontWeight||"400",fontStyle=st.fontStyle||"normal",fontFamily=st.fontFamily||"sans-serif",SCALE=2,pad=Math.ceil(fontSize*1.5),probe=document.createElement("canvas"),pctx=probe.getContext("2d");pctx.font=`${fontStyle} ${fontWeight} ${fontSize*SCALE}px ${fontFamily}`;const m=pctx.measureText(text),left=Math.ceil(m.actualBoundingBoxLeft||0),right=Math.ceil(m.actualBoundingBoxRight||m.width),ascent=Math.ceil(m.actualBoundingBoxAscent||fontSize*SCALE*.9),descent=Math.ceil(m.actualBoundingBoxDescent||fontSize*SCALE*.4),padPx=pad*SCALE;probe.width=Math.max(1,left+right+padPx*2);probe.height=Math.max(1,ascent+descent+padPx*2);const ctx=probe.getContext("2d");ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";ctx.font=`${fontStyle} ${fontWeight} ${fontSize*SCALE}px ${fontFamily}`;ctx.textAlign="left";ctx.textBaseline="alphabetic";ctx.fillStyle=fill;ctx.fillText(text,padPx+left,padPx+ascent);return{canvas:probe,scale:SCALE,inkStart:padPx,inkWidth:left+right,baseline:padPx+ascent,height:probe.height};}
  function extendedPathPoint(path,length,at){const delta=.5;if(at<0){const p=path.getPointAtLength(0),q=path.getPointAtLength(Math.min(length,delta)),dx=q.x-p.x,dy=q.y-p.y,n=Math.hypot(dx,dy)||1;return{x:p.x+dx/n*at,y:p.y+dy/n*at};}if(at>length){const p=path.getPointAtLength(length),q=path.getPointAtLength(Math.max(0,length-delta)),dx=p.x-q.x,dy=p.y-q.y,n=Math.hypot(dx,dy)||1,d=at-length;return{x:p.x+dx/n*d,y:p.y+dy/n*d};}return path.getPointAtLength(at);}
  function drawShapedLineOnPath(ctx,path,shaped){const pathLength=path.getTotalLength(),visualWidth=shaped.inkWidth/shaped.scale;if(!pathLength||!visualWidth)return;const start=(pathLength-visualWidth)/2,destStrip=.5,sourceStrip=destStrip*shaped.scale,overlap=.18;for(let sx=0;sx<shaped.inkWidth;sx+=sourceStrip){const sourceWidth=Math.min(sourceStrip+overlap*shaped.scale,shaped.inkWidth-sx),visualX=sx/shaped.scale,visualStrip=Math.min(destStrip+overlap,visualWidth-visualX),at=start+visualX+visualStrip/2,delta=.35,p=extendedPathPoint(path,pathLength,at),p0=extendedPathPoint(path,pathLength,at-delta),p1=extendedPathPoint(path,pathLength,at+delta),cp=svgToCanvasPoint(p),angle=Math.atan2(p1.y-p0.y,p1.x-p0.x);ctx.save();ctx.translate(cp.x,cp.y);ctx.rotate(angle);ctx.drawImage(shaped.canvas,shaped.inkStart+sx,0,sourceWidth,shaped.height,-visualStrip/2,-shaped.baseline/shaped.scale,visualStrip,shaped.height/shaped.scale);ctx.restore();}}
  function drawCanvasLabels(sourceSvg,ctx){const doc=sourceSvg.ownerDocument;sourceSvg.querySelectorAll("#labels text").forEach(text=>{const tp=text.querySelector("textPath");if(!tp)return;const href=tp.getAttribute("href")||tp.getAttribute("xlink:href");if(!href)return;const path=doc.getElementById(href.replace(/^#/,"")),value=tp.textContent||"";if(!path||!value)return;const st=doc.defaultView.getComputedStyle(text),fill=text.classList.contains("arc-label-adj")?"#17241f":"#43514b";drawShapedLineOnPath(ctx,path,makeShapedLine(value,st,fill));});}
  function makeLabelLayer(sourceSvg){const layer=document.createElement("canvas");layer.width=SIZE;layer.height=SIZE;const lctx=layer.getContext("2d");lctx.imageSmoothingEnabled=true;lctx.imageSmoothingQuality="high";drawCanvasLabels(sourceSvg,lctx);return layer;}
  async function drawSvgFrame(svg,ctx,labelLayer){const xml=new XMLSerializer().serializeToString(prepareSvgClone(svg)),blob=new Blob([xml],{type:"image/svg+xml;charset=utf-8"}),url=URL.createObjectURL(blob);try{const im=new Image();im.src=url;await im.decode();ctx.fillStyle="#fff";ctx.fillRect(0,0,SIZE,SIZE);ctx.drawImage(im,0,0,SIZE,SIZE);ctx.drawImage(labelLayer,0,0);}finally{URL.revokeObjectURL(url);}}
  async function findWebCodecsH264(){if(!window.VideoEncoder||!window.VideoFrame||!window.Mp4Muxer)return null;const codecs=["avc1.420028","avc1.4d0028","avc1.640028","avc1.42e028","avc1.4d4028","avc1.64002a"];for(const codec of codecs){const candidate={codec,width:SIZE,height:SIZE,bitrate:8_000_000,framerate:FPS,avc:{format:"avc"}};try{const result=await VideoEncoder.isConfigSupported(candidate);if(result.supported)return result.config||candidate;}catch(e){}}return null;}
  async function createWebCodecsEncoder(config){const target=new Mp4Muxer.ArrayBufferTarget(),muxer=new Mp4Muxer.Muxer({target,video:{codec:"avc",width:SIZE,height:SIZE,frameRate:FPS},fastStart:"in-memory",firstTimestampBehavior:"strict"});let encoderError=null;const encoder=new VideoEncoder({output:(chunk,meta)=>muxer.addVideoChunk(chunk,meta),error:e=>{encoderError=e;}});encoder.configure(config);return{mode:"webcodecs",async add(canvas,index){if(encoderError)throw encoderError;const timestamp=Math.round(index*1_000_000/FPS),duration=Math.round(1_000_000/FPS),frame=new VideoFrame(canvas,{timestamp,duration});encoder.encode(frame,{keyFrame:index%(FPS*2)===0});frame.close();if(encoder.encodeQueueSize>8)await sleep(0);},async finish(){await encoder.flush();if(encoderError)throw encoderError;encoder.close();muxer.finalize();return new Blob([target.buffer],{type:"video/mp4"});}};}
  function findRecorderMime(){if(!window.MediaRecorder)return null;return["video/mp4;codecs=avc1.42E01E","video/mp4;codecs=avc1","video/mp4"].find(t=>MediaRecorder.isTypeSupported(t))||null;}
  async function transmuxRegularMp4(blob){
    exportBtn.textContent="Making PowerPoint MP4…";
    const mb=await import("https://esm.sh/mediabunny@1.48.0?target=es2022");
    const input=new mb.Input({formats:mb.ALL_FORMATS,source:new mb.BlobSource(blob)}),target=new mb.BufferTarget(),output=new mb.Output({format:new mb.Mp4OutputFormat({fastStart:"in-memory"}),target});
    const conversion=await mb.Conversion.init({input,output});
    if(!conversion.isValid)throw new Error("The browser recorded H.264, but it could not be converted to a standard MP4 file.");
    await conversion.execute();
    return new Blob([target.buffer],{type:"video/mp4"});
  }
  async function createRecorderEncoder(canvas,mime){
    const stream=canvas.captureStream(0),track=stream.getVideoTracks()[0],chunks=[],recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8_000_000});
    const stopped=new Promise((resolve,reject)=>{recorder.addEventListener("dataavailable",e=>{if(e.data?.size)chunks.push(e.data);});recorder.addEventListener("stop",resolve,{once:true});recorder.addEventListener("error",e=>reject(e.error||new Error("MediaRecorder failed")),{once:true});});
    recorder.start();
    return{mode:"mediarecorder",async add(_canvas,_index){track.requestFrame();await sleep(1000/FPS);},async finish(){recorder.stop();await stopped;track.stop();const recorded=new Blob(chunks,{type:mime});if(!recorded.size)throw new Error("The browser produced an empty MP4 recording.");return transmuxRegularMp4(recorded);}};
  }
  async function createMp4Encoder(canvas){const wc=await findWebCodecsH264();if(wc)return createWebCodecsEncoder(wc);const mime=findRecorderMime();if(mime&&canvas.captureStream)return createRecorderEncoder(canvas,mime);throw new Error("This browser cannot create an H.264 MP4 here. Please use a current version of Chrome, Edge or Safari.");}
  function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  async function exportVideo(){
    exportBtn.disabled=true;const original=exportBtn.textContent;exportBtn.textContent="Preparing video…";let iframe;
    try{
      iframe=makeHiddenViewer();const{doc,svg,api}=await waitForViewer(iframe);if(doc.fonts?.ready)await doc.fonts.ready;
      const readyDeadline=Date.now()+20000;while(api.isBusy()&&Date.now()<readyDeadline)await sleep(100);
      if(api.isBusy())throw new Error("The comparison viewer did not finish preparing.");
      api.hideControls();await sleep(150);
      exportBtn.textContent="Preparing labels…";const labelLayer=makeLabelLayer(svg),canvas=document.createElement("canvas");canvas.width=SIZE;canvas.height=SIZE;const ctx=canvas.getContext("2d",{alpha:false});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";await drawSvgFrame(svg,ctx,labelLayer);const mp4=await createMp4Encoder(canvas);let frame=0;
      async function commitFrame(){await drawSvgFrame(svg,ctx,labelLayer);await mp4.add(canvas,frame++);}
      exportBtn.textContent=mp4.mode==="mediarecorder"?"Recording MP4…":"Rendering MP4…";
      api.prepareBeforeStart();
      for(let i=0;i<INITIAL_FRAMES;i++)await commitFrame();
      for(let i=1;i<=SPIRAL_FRAMES;i++){const t=i/SPIRAL_FRAMES;api.setBeforeSpiralProgress(1-Math.pow(1-t,3.2));await commitFrame();}
      api.setBeforeSpiralProgress(1);
      for(let i=0;i<FPS;i++)await commitFrame();
      api.playAfter();
      const maxFrames=FPS*30;
      for(let i=0;i<maxFrames;i++){await commitFrame();if(!api.isBusy()&&api.state()==="after"){for(let j=0;j<FPS;j++)await commitFrame();break;}if(mp4.mode==="webcodecs")await sleep(1000/FPS);}
      exportBtn.textContent="Finalising MP4…";const output=await mp4.finish();downloadBlob(output,`${exportBaseName()}.mp4`);exportBtn.textContent="MP4 exported";setTimeout(()=>exportBtn.textContent=original,2500);
    }catch(error){console.error("NCD Pot Plant comparison video export failed:",error);alert(`Video export failed: ${error.message}`);exportBtn.textContent=original;}finally{if(iframe)iframe.remove();exportBtn.disabled=false;updateFilenamePreview();}
  }
  exportBtn.addEventListener("click",exportVideo);
})();