(() => {
  /* Input order: EL, GBM, PS, ES, IWS, HSG, NOE, LR. Diagram order is fixed clockwise from top centre. */
  const params=new URLSearchParams(window.location.search),requestedLanguage=params.get("lang")||"en",LANGUAGE_CODE=window.NCD_POT_PLANT_LANGUAGES?.[requestedLanguage]?requestedLanguage:"en",language=window.NCD_POT_PLANT_LANGUAGES?.[LANGUAGE_CODE];
  if(!language){console.error(`NCD Pot Plant language "${LANGUAGE_CODE}" could not be loaded.`);return;}
  const INPUT_QC_KEYS=["EL","GBM","PS","ES","IWS","HSG","NOE","LR"],DIAGRAM_QC_KEYS=["LR","EL","ES","GBM","NOE","IWS","PS","HSG"],INPUT_QCS=INPUT_QC_KEYS.map(key=>({key,...language.qcs[key]})),DIAGRAM_QCS=DIAGRAM_QC_KEYS.map(key=>({key,...language.qcs[key]})),DEFAULT_INPUT_SCORES=[67,52,62,59,71,74,43,78],fills=["#477B39","#727145","#926550","#9A5C5E","#786071","#526082","#436777","#44725C"];
  const svg=document.getElementById("viz");if(!svg)return;const svgDefs=svg.querySelector("defs"),wedgesG=document.getElementById("wedges"),labelPathsG=document.getElementById("labelPaths"),labelsG=document.getElementById("labels"),spiralPath=document.getElementById("spiral"),spiralUnder=document.getElementById("spiralUnder"),stopDot=document.getElementById("stopDot");
  const cx=440,cy=440,sectorDeg=45,startDeg=-112.5,minRadius=108,rankStep=36,maxRadius=minRadius+7*rankStep,radialGrowthPerTurn=33,b=radialGrowthPerTurn/(2*Math.PI),animationDurationMs=10000;
  /* Every label, whether 2, 3 or 4 lines, is centred on this same radius. */
  const labelClusterRadius=maxRadius+60,labelLineGap=34;
  let inputScores=readScoresFromUrl()||[...DEFAULT_INPUT_SCORES],spiralPoints=[],animationFrame=null;
  function fullName(qc){return qc.name;}
  function applyInterfaceLanguage(){document.querySelectorAll("[data-i18n]").forEach(el=>{const key=el.getAttribute("data-i18n");if(language.interface[key]!==undefined)el.textContent=language.interface[key];});}
  function inputScoresToMap(scores){const map={};INPUT_QCS.forEach((qc,i)=>map[qc.key]=scores[i]);return map;}
  function diagramScoresFromInput(scores){const map=inputScoresToMap(scores);return DIAGRAM_QCS.map(qc=>map[qc.key]);}
  function readScoresFromUrl(){const p=new URLSearchParams(window.location.search),s=p.get("scores");if(!s)return null;const parsed=s.split(",").map(v=>Number(v.trim()));if(parsed.length===8&&parsed.every(v=>Number.isFinite(v)&&v>=0&&v<=100))return parsed;console.warn("Invalid ?scores= parameter; using defaults.");return null;}
  function updateUrlFromScores(){const p=new URLSearchParams(window.location.search);p.set("scores",inputScores.join(","));history.replaceState(null,"",`${window.location.pathname}?${p.toString()}`);}
  function degToRad(d){return d*Math.PI/180;}function pointPolar(r,t){return[cx+r*Math.cos(t),cy+r*Math.sin(t)];}
  function rankDescending(values){const idx=values.map((_,i)=>i).sort((a,b)=>values[a]-values[b]),ranks=new Array(values.length);idx.forEach((original,pos)=>ranks[original]=pos+1);return ranks;}
  function rankToRadius(rank){return minRadius+(rank-1)*rankStep;}
  function sectorIndexForAngle(theta){let deg=theta*180/Math.PI;while(deg<startDeg)deg+=360;while(deg>=startDeg+360)deg-=360;return Math.floor((deg-startDeg)/sectorDeg);}
  function boundaryCrossingTheta(prevTheta,theta,prevSector){let boundary=degToRad(startDeg+(prevSector+1)*sectorDeg);while(boundary<=prevTheta)boundary+=2*Math.PI;while(boundary>theta)boundary-=2*Math.PI;return boundary;}
  function arcPath(r,a0,a1,reverse=false){let s=degToRad(a0),e=degToRad(a1);if(reverse){const t=s;s=e;e=t;}const p0=pointPolar(r,s),p1=pointPolar(r,e);return`M ${p0[0].toFixed(2)} ${p0[1].toFixed(2)} A ${r} ${r} 0 0 ${reverse?0:1} ${p1[0].toFixed(2)} ${p1[1].toFixed(2)}`;}
  function isBottomHalf(midDeg){let d=midDeg%360;if(d<0)d+=360;return d>0&&d<180;}
  function makeGradient(i,base){const id=`wedgeGrad${i}`;let grad=document.getElementById(id);if(!grad){grad=document.createElementNS("http://www.w3.org/2000/svg","linearGradient");grad.id=id;grad.setAttribute("x1","0%");grad.setAttribute("y1","0%");grad.setAttribute("x2","100%");grad.setAttribute("y2","100%");svgDefs.appendChild(grad);}grad.innerHTML=`<stop offset="0%" stop-color="${base}" stop-opacity="0.92"/><stop offset="100%" stop-color="${base}" stop-opacity="0.72"/>`;return`url(#${id})`;}
  const qcCard=document.getElementById("qcCard"),qcCardName=document.getElementById("qcCardName"),qcCardQuestion=document.getElementById("qcCardQuestion"),qcCardDescription=document.getElementById("qcCardDescription"),qcCardClose=document.getElementById("qcCardClose");
  function openQcCard(index){const qc=DIAGRAM_QCS[index];if(!qcCard||!qc)return;qcCardName.textContent=fullName(qc);qcCardQuestion.textContent=qc.heartQuestion;qcCardDescription.textContent=qc.description;qcCard.classList.add("is-open");qcCard.setAttribute("aria-hidden","false");}
  function closeQcCard(){if(!qcCard)return;qcCard.classList.remove("is-open");qcCard.setAttribute("aria-hidden","true");}
  if(qcCardClose)qcCardClose.addEventListener("click",e=>{e.stopPropagation();closeQcCard();});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeQcCard();});document.addEventListener("click",e=>{if(qcCard?.classList.contains("is-open")&&!qcCard.contains(e.target)&&!e.target.closest(".qc-clickable")&&!e.target.closest(".wedge"))closeQcCard();});
  function draw(){
    const diagramScores=diagramScoresFromInput(inputScores),ranks=rankDescending(diagramScores),minVal=Math.min(...diagramScores),maxVal=Math.max(...diagramScores),minIdx=diagramScores.indexOf(minVal),maxIdx=diagramScores.indexOf(maxVal);wedgesG.innerHTML="";labelPathsG.innerHTML="";labelsG.innerHTML="";
    diagramScores.forEach((score,i)=>{
      const a0=startDeg+i*sectorDeg,a1=a0+sectorDeg,mid=(a0+a1)/2,r=rankToRadius(ranks[i]),p0=pointPolar(r,degToRad(a0)),p1=pointPolar(r,degToRad(a1));
      const path=document.createElementNS("http://www.w3.org/2000/svg","path");path.setAttribute("d",`M ${cx} ${cy} L ${p0[0]} ${p0[1]} A ${r} ${r} 0 0 1 ${p1[0]} ${p1[1]} Z`);path.setAttribute("fill",makeGradient(i,fills[i]));path.setAttribute("class","wedge");path.setAttribute("data-qc-index",i);path.setAttribute("tabindex","0");path.setAttribute("role","button");path.addEventListener("click",e=>{e.stopPropagation();openQcCard(i);});path.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openQcCard(i);}});wedgesG.appendChild(path);
      const bottom=isBottomHalf(mid),reverse=bottom,arcStart=a0+3.5,arcEnd=a1-3.5,qc=DIAGRAM_QCS[i],lines=Array.isArray(qc.lines)?qc.lines.slice(0,4):[];
      if(lines.length<2)console.warn(`${qc.key} should define at least two label lines.`);if(qc.lines?.length>4)console.warn(`${qc.key} defines more than four label lines; only the first four are rendered.`);
      /* Keep the visual centre of every cluster at one common radius. On the bottom half the radial order is reversed so the linguistic reading order remains top-to-bottom. */
      const centreIndex=(lines.length-1)/2;
      lines.forEach((line,lineIndex)=>{
        const offset=(centreIndex-lineIndex)*labelLineGap,radius=labelClusterRadius+(bottom?-offset:offset),arcId=`labelArc${i}_${lineIndex}`,arc=document.createElementNS("http://www.w3.org/2000/svg","path");
        arc.id=arcId;arc.setAttribute("d",arcPath(radius,arcStart,arcEnd,reverse));arc.setAttribute("fill","none");arc.setAttribute("stroke","none");labelPathsG.appendChild(arc);
        const text=document.createElementNS("http://www.w3.org/2000/svg","text");text.setAttribute("class",`${line.emphasis?"arc-label-adj":"arc-label-noun"} qc-clickable`);const baseFontSize=line.emphasis?42:34;text.setAttribute("font-size",String(baseFontSize*(language.labelScale??1)));text.setAttribute("data-qc-index",i);text.setAttribute("tabindex","0");text.setAttribute("role","button");text.addEventListener("click",e=>{e.stopPropagation();openQcCard(i);});text.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openQcCard(i);}});
        const tp=document.createElementNS("http://www.w3.org/2000/svg","textPath");tp.setAttribute("href",`#${arcId}`);tp.setAttribute("startOffset","50%");tp.setAttribute("text-anchor","middle");tp.textContent=line.text;text.appendChild(tp);labelsG.appendChild(text);
      });
    });
    const minText=document.getElementById("minText"),maxText=document.getElementById("maxText");if(minText)minText.textContent=`${fullName(DIAGRAM_QCS[minIdx])} — ${minVal}`;if(maxText)maxText.textContent=`${fullName(DIAGRAM_QCS[maxIdx])} — ${maxVal}`;return{ranks,minIdx};
  }
  function buildSpiralPoints(ranks,minIdx){const theta0=-Math.PI/2,thetaMax=theta0+Math.PI*60,step=.0045,pts=[[cx,cy]],minBoundary=rankToRadius(ranks[minIdx]);let prevTheta=theta0,prevSector=sectorIndexForAngle(prevTheta);for(let theta=theta0+step;theta<=thetaMax;theta+=step){const currentSector=sectorIndexForAngle(theta);if(currentSector!==prevSector){const crossingTheta=boundaryCrossingTheta(prevTheta,theta,prevSector),crossingR=b*(crossingTheta-theta0);if(currentSector===minIdx&&crossingR>minBoundary){pts.push(pointPolar(crossingR,crossingTheta));return pts;}}const r=b*(theta-theta0);pts.push(pointPolar(r,theta));prevTheta=theta;prevSector=currentSector;}return pts;}
  function pointsToPath(points,count=points.length){const n=Math.max(1,Math.min(count,points.length));let d=`M ${points[0][0].toFixed(2)} ${points[0][1].toFixed(2)}`;for(let i=1;i<n;i++)d+=` L ${points[i][0].toFixed(2)} ${points[i][1].toFixed(2)}`;return d;}
  function setSpiralProgress(progress){const p=Math.max(0,Math.min(1,progress)),count=p<=0?1:Math.max(2,Math.floor(p*(spiralPoints.length-1))+1),d=pointsToPath(spiralPoints,count);spiralPath.setAttribute("d",d);spiralUnder.setAttribute("d",d);const tip=spiralPoints[count-1]||[cx,cy];stopDot.setAttribute("cx",tip[0]);stopDot.setAttribute("cy",tip[1]);stopDot.style.opacity=p<=0?0:(p<1?.95:1);}
  function setFullSpiral(){setSpiralProgress(1);}function animateSpiral(){if(animationFrame)cancelAnimationFrame(animationFrame);setSpiralProgress(0);const startTime=performance.now();function frame(now){const t=Math.min(1,(now-startTime)/animationDurationMs),progress=1-Math.pow(1-t,3.2);setSpiralProgress(progress);if(t<1)animationFrame=requestAnimationFrame(frame);else animationFrame=null;}animationFrame=requestAnimationFrame(frame);}function render(animate=true){const{ranks,minIdx}=draw();spiralPoints=buildSpiralPoints(ranks,minIdx);if(animate)animateSpiral();else setFullSpiral();}
  function buildControls(){const sliders=document.getElementById("sliders");if(!sliders)return;sliders.innerHTML="";INPUT_QCS.forEach((qc,i)=>{const row=document.createElement("div");row.className="row";row.innerHTML=`<label><span>${fullName(qc)}</span><strong id="value${i}">${inputScores[i]}</strong></label><input aria-label="${fullName(qc)}" type="range" min="0" max="100" value="${inputScores[i]}">`;const input=row.querySelector("input");input.addEventListener("input",e=>{inputScores[i]=Number(e.target.value);document.getElementById(`value${i}`).textContent=inputScores[i];updateUrlFromScores();render(false);});input.addEventListener("change",()=>render(true));sliders.appendChild(row);});}
  function syncControls(){document.querySelectorAll("#sliders input").forEach((input,i)=>{input.value=inputScores[i];const value=document.getElementById(`value${i}`);if(value)value.textContent=inputScores[i];});updateUrlFromScores();}function setScores(newScores){inputScores=[...newScores];syncControls();render(true);}
  document.getElementById("animateBtn")?.addEventListener("click",animateSpiral);document.getElementById("randomBtn")?.addEventListener("click",()=>setScores(inputScores.map(()=>Math.round(35+Math.random()*55))));document.getElementById("closeBtn")?.addEventListener("click",()=>setScores([50,51,52,53,54,55,56,57]));document.getElementById("balancedBtn")?.addEventListener("click",()=>setScores([69,68,67,72,73,74,70,71]));
  const languageSelect=document.getElementById("languageSelect");if(languageSelect){languageSelect.value=LANGUAGE_CODE;languageSelect.addEventListener("change",event=>{const p=new URLSearchParams(window.location.search);p.set("lang",event.target.value);window.location.search=p.toString();});}applyInterfaceLanguage();buildControls();syncControls();
  const isViewer=document.body.classList.contains("viewer"),growBtn=document.getElementById("growBtn");
  if(isViewer){const{ranks,minIdx}=draw();spiralPoints=buildSpiralPoints(ranks,minIdx);setSpiralProgress(0);window.NCDPotPlantExport={setWedgeOpacity(value){document.querySelectorAll(".wedge").forEach(w=>{w.style.transition="none";w.style.transform="scale(1)";w.style.opacity=String(Math.max(0,Math.min(.70,value)));});},setSpiralProgress(progress){if(animationFrame){cancelAnimationFrame(animationFrame);animationFrame=null;}setSpiralProgress(progress);},setSpiralTone(tone){document.body.classList.remove("growing","settled");if(tone==="olive")document.body.classList.add("settled");else document.body.classList.add("growing");},hideControls(){if(growBtn)growBtn.style.display="none";if(qcCard)qcCard.style.display="none";}};
    if(growBtn)growBtn.addEventListener("click",()=>{document.body.classList.remove("settled","growing");const firstRun=!document.body.classList.contains("has-grown");growBtn.classList.add("is-running");if(firstRun){document.body.classList.add("revealing");window.setTimeout(()=>{document.body.classList.remove("revealing");document.body.classList.add("growing");animateSpiral();},1000);}else{document.body.classList.add("growing");animateSpiral();}const preGrowthDelay=firstRun?1000:0;window.setTimeout(()=>{window.setTimeout(()=>{document.body.classList.remove("growing");document.body.classList.add("settled","has-grown");},500);window.setTimeout(()=>{const icon=growBtn.querySelector(".grow-icon"),label=growBtn.querySelector(".grow-label");if(icon)icon.textContent="🌱";if(label)label.textContent=language.interface.watchAgain;growBtn.classList.add("is-replay");growBtn.classList.remove("is-running");},900);},preGrowthDelay+animationDurationMs);});
  }else render(true);
})();
